FROM node:22-bullseye-slim

WORKDIR /app

# Copiar package.json
COPY package*.json ./

# Instalar dependências (node_modules/ para Linux)
RUN npm install

# Copiar Prisma e gerar cliente
COPY prisma ./prisma
RUN npx prisma generate

# Copiar código (ignora node_modules graças ao .dockerignore)
COPY . .

EXPOSE 4000

CMD ["npm", "run", "dev"]